### ISSUE TITLE
`Validator.collect` or `Validator.unfold` that will `compose` multiple validators

### ISSUE THREAD

**Issue by xperiandri** [pimbrouwers/Validus#13]

**Comment by pimbrouwers** [comment]
This already exists in the `<+>` operator in combination with the applicative builder `validate {}`.

**Comment by xperiandri** [comment]
Yes, but sometimes it is easier to express as a list

**Comment by pimbrouwers** [comment]
I am not sure I follow?

**Comment by xperiandri** [comment]
Imagine we have 4 validators composed with `<+>`
3 of them produced errors
That means https://github.com/pimbrouwers/Validus/blob/a03a95ab48ddbd1fcd60f267c1682fb14b18b1d0/src/Validus/Validus.fs#L36-L37 will be called 2 times producing a list twice while having `Validator.unfold` it would produce only a single list to pass to https://github.com/pimbrouwers/Validus/blob/a03a95ab48ddbd1fcd60f267c1682fb14b18b1d0/src/Validus/Validus.fs#L37

So that for each error result we allocate (validator count - 2) lists instead of only 1

**Comment by pimbrouwers** [comment]
See solution for #12
