### ISSUE TITLE
lessThanLen with the default error messages has wrong message

### ISSUE THREAD

**Issue by kyryloboiev** [pimbrouwers/Validus#16]
```
/// Validate string length is less than provided value with the
/// default error message
member _.lessThanLen (max : int) (field : string) (input : string) =
    let msg field =
    sprintf "%s must be at least %i characters" field max
    x.lessThanLen max msg field input
```
If i right  "must be at least" mean than string must be longer than 100
But more correct message for this is : "must be less than"

**Comment by xperiandri** [comment]
``` F#
sprintf "%s must be at most %i characters" field max
```
**at most**

**Comment by xperiandri** [comment]
@pimbrouwers I also propose to migrate to string interpolation and wrap a value into single quotes like this
``` F#
$"'%s{field}' must be at most %i{max} characters"
```

**Comment by xperiandri** [comment]
@pimbrouwers if you are OK with the approach we will prepare a PR

**Comment by pimbrouwers** [comment]
Fixed.

**Comment by pimbrouwers** [comment]
> @pimbrouwers I also propose to migrate to string interpolation and wrap a value into single quotes like this
> 
> ```fsharp
> $"'%s{field}' must be at most %i{max} characters"
> ```

Not a huge fan of what the compiler does for string interpolation. I do think the single quote idea is interesting. I would be curious to look into how other libraries, say FluentValidation for example, handles this.

**Comment by pimbrouwers** [comment]
> > @pimbrouwers I also propose to migrate to string interpolation and wrap a value into single quotes like this
> > ```fsharp
> > $"'%s{field}' must be at most %i{max} characters"
> > ```
> 
> Not a huge fan of what the compiler does for string interpolation. I do think the single quote idea is interesting. I would be curious to look into how other libraries, say FluentValidation for example, handles this.

Looks like they quote the field name with single quotes.

![image](https://user-images.githubusercontent.com/4595453/186247996-9795c20d-451d-47fc-954a-b41f260ae0ef.png)

**Comment by xperiandri** [comment]
Microsoft always does that in logger messages
