### ISSUE TITLE
Order of arguments for <!>, i.e. the map operator

### ISSUE THREAD

**Issue by abelbraaksma** [pimbrouwers/Validus#17]
Currently, the `<!>` operator is defined as `let inline (<!>) f x = Result.map f x`. But that leads to code like this:

```
let validateChild a b = (fun x -> Child) <!> ageValidator a b
```

Whereas this feels more natural:

```
let (<!>) f x = Result.map x f
let validateChild a b = ageValidator a b <!> fun x -> Child
```

Not sure how long the operator is around and "used in the wild", but it seems to me the intention was the latter of the two options above.

**Comment by pimbrouwers** [comment]
From our other discussion in #11 and on Slack, we'll be replacing all of the existing operators.
