### ISSUE TITLE
typo in Operator.fs

### ISSUE THREAD

**Issue by ElucidataFSharp** [pimbrouwers/Validus#19]
let (.>>) v1 v2 = pickLeft v1 v2
    let (>>.) v1 v2 = pickLeft v1 v2

**Comment by pimbrouwers** [comment]
Thanks! This just a stub from some code in #11. @abelbraaksma is submitting a PR with touch ups before we put this into production.

**Comment by pimbrouwers** [comment]
Addressed in #20.

**Comment by abelbraaksma** [comment]
Correct. I noticed that typo when writing the tests, thanks for reporting @ElucidataFSharp.
