### ISSUE TITLE
Check.String.exists function

### ISSUE THREAD

**Issue by sheridanchris** [pimbrouwers/Validus#21]
It may be useful to add the function ``Check.String.exists``.
Some example use cases would be:
```fsharp
Check.String.exists Char.IsUpper
Check.String.exists Char.IsNumber

let symbolCharacters = "!@#$%^&*()_-+={[}]|\\'\";:/?.>,<"
Check.String.exists symbolCharacters.Contains
```

I can PR this if you think it's a good idea.

**Comment by pimbrouwers** [comment]
You could always use pattern for this as well if you wanted to use one of the builtins. Or, create a bespoke validator in your code.

**Comment by pimbrouwers** [comment]
If you go the bespoke wrote share it here so it stands through the annals of time 🙃

**Comment by sheridanchris** [comment]
I ended up going with this for reusability.
```fs
let stringContainsValidator (f: char -> bool) (message: ValidationMessage) =
  let rule (value: string) = value |> Seq.exists f
  Validator.create message rule
  ```

This can easily be made generic and work for any sequence 😄

**Comment by pimbrouwers** [comment]
Light bulb!

Let's add a "Seq" validator, to match the form of the List validator. 

You want to PR it?

**Comment by sheridanchris** [comment]
Good idea. I'll definitely PR it
