### ISSUE TITLE
Usage of the validation library for different language than English

### ISSUE THREAD

**Issue by wallymathieu** [pimbrouwers/Validus#23]
Hi! Great reading your library!

It would perhaps be neat to be able to configure the defaults in some way that does not require you to make your own Default module?

https://github.com/pimbrouwers/Validus/blob/6c19608d137fb8f893f72932d8662d11fc8f6cd3/src/Validus/Validators.fs#L373-L385

**Comment by sheridanchris** [comment]
You can supply your own messages with ``Check.WithMessage``
Here's a practical example:
```fsharp
let emailPatternValidator =
    Check.WithMessage.String.pattern @"[^@]+@[^\.]+\..+" (sprintf "Please provide a valid %s")
```
