### ISSUE TITLE
Fable compatibility

### ISSUE THREAD

**Issue by sheridanchris** [pimbrouwers/Validus#24]
It would be nice if this library was compatible with Fable.
As far as I'm aware, there isn't any Fable-incompatible code so adding:
```xml
<!-- Add source files to "fable" folder in Nuget package -->
<ItemGroup>
    <Content Include="*.fsproj; **\*.fs; **\*.fsi" PackagePath="fable\" />
</ItemGroup>
```
Should be enough.

You can read more about this [here](https://fable.io/docs/your-fable-project/author-a-fable-library.html)

**Comment by pimbrouwers** [comment]
Cool! I don't know anything about Fable in production, so this is great. I'll add this into the next release!
