### ISSUE TITLE
Define all error messages as public static functions

### ISSUE THREAD

**Issue by xperiandri** [pimbrouwers/Validus#26]
Sometimes you just want to reuse an existing message like this
https://github.com/pimbrouwers/Validus/blob/19a0af2ae3970b4095794e53202d6ac2cae1dff3/src/Validus/Validators.fs#L309

For example in a unit test

**Comment by pimbrouwers** [comment]
These are now accessible in the `Validus` namespace via the `ValidationMessages` [module](https://github.com/pimbrouwers/Validus/blob/d9faf798d9dc2095f33f9fc59dc9339e9cdd73ad/src/Validus/Core.fs#L23).

I will roll these out with v4.1.0.

**Comment by xperiandri** [comment]
Perfect! Thank you very much!

**Comment by pimbrouwers** [comment]
Always my pleasure Andrii!
