### ISSUE TITLE
Length error message seems backwards?

### ISSUE THREAD

**Issue by isaacabraham** [pimbrouwers/Validus#27]
```fsharp
#r "nuget:Validus"

open Validus

let validator = Check.String.greaterThanLen 8
validator "Email Address" "foo"
```

I assume that this should enforce that the string must be greater than 8 characters? It does, but the error message is misleading / incorrect:

```
Error
    { ValidationErrors =
   map [("Email Address", ["'Email Address' must not execeed 8 characters"])] }
```

Surely it should be "must be at least 8 characters" or similar?

The `lessThanLen` message seems to be a typo too:

```
[("Email Address", ["'Email Address' must be at less than 8 characters"])] }
```

**Comment by pimbrouwers** [comment]
Thanks Isaac. Did not notice that the text had gotten twisted around there. I just pushed 4.0.2 to NuGet which fixes this.
