### ISSUE TITLE
Basic "mandatory" checker?

### ISSUE THREAD

**Issue by isaacabraham** [pimbrouwers/Validus#28]
Is there a built-in validator that works with an optional field that needs to be mandatory i.e. `Option<'T> -> Validator` or something? If Some x -> Ok x, None -> ValidationError etc.

**Comment by pimbrouwers** [comment]
Hey! There sure is. You're looking for:

https://github.com/pimbrouwers/Validus/blob/19a0af2ae3970b4095794e53202d6ac2cae1dff3/src/Validus/Check.fs#L93-L99

**Comment by isaacabraham** [comment]
Thanks

**Comment by isaacabraham** [comment]
Why does this take in a validator though? I just want something like:

```fsharp
match x with
| Some v -> Ok v
| None -> Error "field" "message"
```

Or am I missing something here (entirely possible)?

**Comment by pimbrouwers** [comment]
Sorry this took me some time, Always busy around the holiday's.

You raise a really good question. I suppose that I initially thought you'd always be "checking" the value when you inspect it. For options I figured most people would still want to do the same, if there was a value, giving them to option to make the field optional or required overall, via these helpers.

You could easily create your own function for this though. Something like:

```fsharp
let exists fieldname value = 
    let msg = sprintf "The %s input must have a value"
    let rule (x : 'a option) = Option.isSome x
    let validator = Validator.create msg rule
    validator fieldname value
```

**Comment by pimbrouwers** [comment]
Added built in support for this via `Check.Option.isSome`, `Check.Option.isNone` (with sister functions for `voption`'s `Check.VOption.isSome` and `Check.VOption.IsNone`).

Will roll this out in v4.1.0.
