### ISSUE TITLE
Getting error in custom validator - Validators.Default.String.pattern

### ISSUE THREAD

**Issue by AnalyzeNCode** [pimbrouwers/Validus#4]
I was just trying the sample of custom validator from the document but getting following compile time error.
Am I missing anything?

![image](https://user-images.githubusercontent.com/9932402/124084302-79d11200-da6c-11eb-8f7c-aa0081ca6195.png)

**Comment by pimbrouwers** [comment]
Hi Subhash! 

Thank you for reaching out. Sorry for the trouble. It appears you're missing the operators import to support the usage of `<+>`. If you add `open Validus.Operators` to your imports, it should work!

**Comment by AnalyzeNCode** [comment]
Oh, it's silly mistake by me. 
I have open the operators and the error has resolved.
@pimbrouwers Thanks for the quick response.

**Comment by AnalyzeNCode** [comment]
@pimbrouwers 
The IDE (VS Code with Ionide) showing error as mentioned below in screenshot but the program execute successfully.

![image](https://user-images.githubusercontent.com/9932402/124132736-be75a100-da9e-11eb-8d82-6049b3acfb84.png)

Actually, I tried by reloading window and also by restarting the vscode but still the IDE level error is there.

It's not like an issue in validus but just wanted to point out.

Edited:
By adding None after pattern string resolves the IDE error but it generates error at compile time.
For ex. 
If the code is like,
let emailValidator = Validators.Default.String.betweenLen 8 512 <+> Validators.Default.String.pattern "@" None

Then there is no error in IDE, but when compile, I am getting following error.

ValidusInbuiltValidators.fs(10,13): error FS0001: Type mismatch. Expecting a 'Validator<string>' but given a
    'string -> ValidationResult<string>'
The type 'string -> ValidationResult<string>' does not match the type 'ValidationResult<string>'

**Comment by pimbrouwers** [comment]
No problem at all my friend! That is very interesting. I will try and repro this in the afternoon when I have some free time.

Appreciate you troubleshooting with me!

**Comment by pimbrouwers** [comment]
Just tested this out in VS Code and it worked for me: 
![image](https://user-images.githubusercontent.com/4595453/124157993-65d6e180-da67-11eb-919c-7cbb31a9dcd7.png)

In looking at your screenshots again, I see the problem. Your file extension is `.fs` but should be `.fsx`.

**Comment by AnalyzeNCode** [comment]
I execute code by selecting and then Alt+Enter.
I don't know the difference between both approach. Like, code in .fs file and code in .fsx. But I will try the in .fsx as well.

My most of experience is in C# and have just recently start programming in F# so don't have much idea about these concepts.

**Comment by AnalyzeNCode** [comment]
I have checked in .fsx and it's working. Thanks.
